### ISSUE TITLE
Add additional authentication options for each provider in `cmd/internal`

### ISSUE THREAD

**Issue by inkel** [grafana/unused#72]
Currently each provider is opinionated in how it authenticates, for example:

- GCP needs you to authenticate via the `gcloud` CLI.
- AWS needs a valid profile in `~/.aws/config` and `~/.aws/credentials`.
- Azure needs authentication via the `az` CLI.

All these providers have other means of authentication; we should try and add those as well.

**THIS ISSUE NEEDS MORE RESEARCH AND DOCUMENTATION**

```[tasklist]
### Tasks
- [ ] Add additional authentication options for GCP
- [ ] Add additional authentication options for AWS
- [ ] Add additional authentication options for Azure
```
